### ISSUE TITLE
Capistrano connection refused when consecutive connections too fast

### ISSUE THREAD

**Issue by cycomarcooo** [ezekg/theme-juice-cli#63]
Hi, I'm facing an issue while trying to push db on remote server. First connection to backup the db is working well (as well as others deploy commands like env:push etc.) but the second connection for db:init is refused (Errno::ECONNREFUSED). 
It seems to be linked to sshd configuration (remote server) that refused connections coming to fast, concurrent connection. As I can't config sshd on remote serveur, I'd like to know if there is a chance to configure capistrano through the Juicefile to tune [sshkit connection pull](https://github.com/capistrano/sshkit/pull/70) or something to wait some time between consecutive ssh connections?
Thanks

```
$ tj deploy staging db:push
 … Configuring Capistrano
 … Configuring stage 'staging'
 … Configuring VM stage
 … Loading Capistrano
 … Loading Capistrano tasks
 … Invoking Capistrano
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke load:settings (first_time)
** Execute load:settings
** Invoke db:push (first_time)
** Execute db:push
** Invoke db:backup (first_time)
** Execute db:backup
INFO [82f5f17e] Running /usr/bin/env mkdir -p tmp as user@siteground-staging
INFO [82f5f17e] Finished in 0.102 seconds with exit status 0 (successful).
INFO [046131bb] Running /usr/bin/env wp db export tmp/2016-04-29-09-42-11.staging.backup.sql --add-drop-table as user@siteground-staging
INFO [046131bb] Finished in 0.195 seconds with exit status 0 (successful).
INFO [91ffa09b] Running /usr/bin/env mkdir -p backup as marco@localhost
INFO [91ffa09b] Finished in 0.018 seconds with exit status 0 (successful).
INFO Downloading backup/2016-04-29-09-42-11.staging.backup.sql 100.0%
INFO [84f0f301] Running /usr/bin/env rm tmp/2016-04-29-09-42-11.staging.backup.sql as user@siteground-staging
INFO [84f0f301] Finished in 0.101 seconds with exit status 0 (successful).
** Invoke db:init (first_time)
** Execute db:init
/Library/Ruby/Gems/2.0.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:70:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
	from /Library/Ruby/Gems/2.0.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:70:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:70:in `block in initialize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:97:in `timeout'
	from /Library/Ruby/Gems/2.0.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:67:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/net-ssh-2.9.4/lib/net/ssh.rb:207:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/net-ssh-2.9.4/lib/net/ssh.rb:207:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/backends/connection_pool.rb:59:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/backends/connection_pool.rb:59:in `with'
	from /Library/Ruby/Gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/backends/netssh.rb:143:in `with_ssh'
	from /Library/Ruby/Gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/backends/netssh.rb:96:in `execute_command'
	from /Library/Ruby/Gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:137:in `block in create_command_and_execute'
	from /Library/Ruby/Gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:137:in `tap'
	from /Library/Ruby/Gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:137:in `create_command_and_execute'
	from /Library/Ruby/Gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:69:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:74:in `within'
	from /Library/Ruby/Gems/2.0.0/gems/theme-juice-0.24.4/lib/theme-juice/tasks/capistrano/db.rb:43:in `block (3 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
	from /Library/Ruby/Gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:29:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
```

**Comment by ezekg** [comment]
It's connecting to the remote server just fine, seeing as the backup went smoothly. It actually looks like it's failing on your vagrant environment, while it creates an export of the local database to push ([line #43](https://github.com/ezekg/theme-juice-cli/blob/master/lib/theme-juice/tasks/capistrano/db.rb?ts=2#L43)). Can you SSH into it? Your `Juicefile` should contain a `vagrant` stage; are the credentials there correct?

**Comment by cycomarcooo** [comment]
My fault sorry, you're right. I look into the wrong direction. I left an old entry in my local hosts file that has the same domain as the one I tried to deploy. I didn't notice the issue while accessing the site  through a browser thanks to / because of landrush.
Thanks for your help.

**Comment by ezekg** [comment]
No problem at all. Glad it's resolved. 👌
