### ISSUE TITLE
uploads:pull error

### ISSUE THREAD

**Issue by cycomarcooo** [ezekg/theme-juice-cli#73]
Hi, I got the following error when trying to perform tj deploy staging uploads:pull
All other commands are working well (db:pull/push, env:pull/push and so on)
Did I miss something?

I'm using tj 0.28.0

```
 … Configuring Capistrano
 … Configuring stage 'staging'
 … Configuring VM stage
 … Loading Capistrano
 … Loading Capistrano tasks
 … Loading custom Capistrano tasks
 … Invoking Capistrano
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke load:settings (first_time)
** Execute load:settings
** Invoke uploads:pull (first_time)
** Execute uploads:pull
** Invoke dir:pull (first_time)
** Execute dir:pull
** Invoke dir:init (first_time)
** Execute dir:init
  INFO [4e7b0f0f] Running /usr/bin/env mkdir -p tmp as marco@localhost
  INFO [4e7b0f0f] Finished in 0.004 seconds with exit status 0 (successful).
  INFO [5161d9ae] Running /usr/bin/env mkdir -p tmp as jinbieur@c15388.sgvps.net
  INFO [5161d9ae] Finished in 0.109 seconds with exit status 0 (successful).
  INFO [f71e0d89] Running /usr/bin/env mkdir -p app/uploads as marco@localhost
  INFO [f71e0d89] Finished in 0.005 seconds with exit status 0 (successful).
/Users/marco/.rvm/gems/ruby-2.2.0/gems/net-scp-1.2.1/lib/net/scp/download.rb:19:in `download_start_state': cannot recursively download to an in-memory location (Net::SCP::Error)
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/net-scp-1.2.1/lib/net/scp.rb:369:in `block (3 levels) in start_command'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/connection/channel.rb:324:in `call'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/connection/channel.rb:324:in `process'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/connection/session.rb:223:in `block in preprocess'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/connection/session.rb:223:in `each'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/connection/session.rb:223:in `preprocess'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/connection/session.rb:206:in `process'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/connection/session.rb:170:in `block in loop'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/connection/session.rb:170:in `loop'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/connection/session.rb:170:in `loop'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/net-ssh-2.9.4/lib/net/ssh/connection/channel.rb:269:in `wait'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/net-scp-1.2.1/lib/net/scp.rb:321:in `download!'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/sshkit-1.11.1/lib/sshkit/backends/netssh.rb:57:in `block in download!'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/sshkit-1.11.1/lib/sshkit/backends/connection_pool.rb:61:in `with'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/sshkit-1.11.1/lib/sshkit/backends/netssh.rb:155:in `with_ssh'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/sshkit-1.11.1/lib/sshkit/backends/netssh.rb:56:in `download!'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/theme-juice-0.27.2/lib/theme-juice/tasks/capistrano/dir.rb:87:in `block (3 levels) in <top (required)>'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/sshkit-1.11.1/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/sshkit-1.11.1/lib/sshkit/backends/abstract.rb:29:in `run'
       	from /Users/marco/.rvm/gems/ruby-2.2.0/gems/sshkit-1.11.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
```

**Comment by ezekg** [comment]
That's an odd error. What happens when you run it with the `--gzip` flag? Who are you hosting with?

**Comment by cycomarcooo** [comment]
It works great with -gzip option. I'm hosting with siteground.

**Comment by ezekg** [comment]
Great. Could you create a gist of your `Juicefile` configuration? You can remove any server information, of course. I just need something to try to reproduce.

**Comment by cycomarcooo** [comment]
Here it is: https://gist.github.com/cycomarcooo/d657b252dc5466133ddfcb95f349aea3

**Comment by ezekg** [comment]
Thanks, it's fixed. I'm cutting a new release now! 👍
